# Documentation build module (docs partition only)
#
# Builds an mdBook site with:
# - Module options (flake-parts, deploy/NixOS/HM/system-manager, NixOS container)
# - Markdown content pages
# - Examples from the examples/ directory
# - GitHub Actions workflow for Pages deployment
{
  inputs,
  lib,
  config,
  ...
}:
let
  flakeModules = config.flake.modules;
in
{
  config = {
    perSystem =
      {
        config,
        pkgs,
        system,
        ...
      }:
      let
        import-tree = inputs.import-tree;

        # --- Flake-parts options (oci.*) ---
        # Uses the composed module from flake.modules.flake.nix-oci.
        flakePartsEval =
          inputs.flake-parts.lib.evalFlakeModule
            {
              inputs = inputs // {
                self = { };
              };
            }
            {
              imports = [
                flakeModules.flake.nix-oci
              ];
              systems = [ system ];
            };

        perSystemOptions = flakePartsEval.options.perSystem.type.getSubOptions [ ];

        # Rewrite /nix/store/<hash>-source/path -> clickable GitHub link
        repoUrl = "https://github.com/Dauliac/nix-oci/blob/main";
        cleanupOptions =
          opt:
          let
            cleanDecl =
              decl:
              let
                declStr = toString decl;
                match = builtins.match "/nix/store/[a-z0-9]+-source/(.*)" declStr;
              in
              if match != null then
                let
                  raw = builtins.head match;
                  parts = builtins.match "([^,]+),? ?(via .*)?" raw;
                  relPath = if parts != null then builtins.head parts else raw;
                in
                {
                  url = "${repoUrl}/${relPath}";
                  name = relPath;
                }
              else
                decl;
          in
          opt
          // {
            visible = (opt.visible or true) && !(opt.internal or false);
            declarations = map cleanDecl opt.declarations;
          };

        # Top-level oci options
        topLevelDoc = pkgs.nixosOptionsDoc {
          options = {
            inherit (flakePartsEval.options) oci;
          };
          transformOptions = cleanupOptions;
        };

        # Per-system oci options
        perSystemDoc = pkgs.nixosOptionsDoc {
          options = {
            inherit (perSystemOptions) oci;
          };
          transformOptions = cleanupOptions;
        };

        # nix-lib functions (lib.oci.*) -- auto-generated by nix-lib framework
        nixLibDoc = config.nix-lib.docs.package;

        # Container sub-options (from the deferred module)
        containerSubOptions =
          let
            allOpts = config.oci.perContainer.getSubOptions [ ];
          in
          builtins.removeAttrs allOpts [
            "perTag"
            "tagConfigs"
            "perArch"
            "archConfigs"
            "_containerName"
            "_module"
          ];

        containerDoc = pkgs.nixosOptionsDoc {
          options = containerSubOptions;
          transformOptions = cleanupOptions;
        };

        # --- Deploy module options (oci.*) ---
        # The deploy submodule imports shared options (_options/) + deploy extensions (_containers/).
        # We resolve import-tree here and provide nix2container + ociLib via specialArgs.
        sharedOptions = import-tree ./modules/oci/containers/_options;
        deployExtensions = import-tree ./modules/deploy/nix-oci/options/_containers;

        # Minimal ociLib stub for option declarations (only needed for default values).
        # Uses the shared pure library where possible; stubs for derivation-producing
        # functions that can't evaluate during docs generation.
        ociLib = (import ./lib/oci.nix { inherit lib; }) // {
          mkShadowSetup = _: [ ];
          mkRoot = _: null;
          mkHardenedConfigs = _: [ ];
          mkSeccompProfile = _: null;
        };

        deployOptionModules = [
          (
            { lib, ... }:
            {
              options.oci.enable = lib.mkEnableOption "nix-oci container deployment";
            }
          )
          (
            { lib, ... }:
            {
              options.oci.backend = lib.mkOption {
                type = lib.types.enum [
                  "docker"
                  "podman"
                ];
                default = "podman";
                description = "Container runtime backend to load and run images.";
              };
            }
          )
          (
            { lib, ... }:
            {
              options.oci.containers = lib.mkOption {
                type = lib.types.attrsOf (
                  lib.types.submoduleWith {
                    modules = [
                      sharedOptions
                      deployExtensions
                    ];
                    specialArgs = {
                      inherit pkgs ociLib;
                      nix2container = inputs.nix2container.packages.${system}.nix2container;
                    };
                  }
                );
                default = { };
                description = ''
                  OCI containers to build, load, and optionally run.
                  Each entry builds an image via nix2container and creates
                  a systemd service to load it into the container runtime.
                '';
              };
            }
          )
        ];

        deployEval = lib.evalModules {
          modules = deployOptionModules ++ [
            {
              options._module.args = lib.mkOption { internal = true; };
              config._module.check = false;
            }
          ];
        };

        deployDoc = pkgs.nixosOptionsDoc {
          options = {
            inherit (deployEval.options) oci;
          };
          transformOptions = cleanupOptions;
        };

        # --- NixOS container module options (oci.container.*) ---
        # Use import-tree to discover _nixos/oci modules, same as eval.nix does.
        ociNixOSModule = import-tree ./modules/_nixos-oci;

        nixosContainerEval = lib.evalModules {
          modules = [
            ociNixOSModule
            inputs.nix-lib.nixosModules.default
            {
              options._module.args = lib.mkOption { internal = true; };
              config._module = {
                check = false;
                args = {
                  pkgs = lib.modules.mkForce pkgs;
                };
              };
            }
          ];
        };

        nixosContainerDoc = pkgs.nixosOptionsDoc {
          options = {
            inherit (nixosContainerEval.options) oci;
          };
          transformOptions = cleanupOptions;
        };

        # Extract nix-lib metadata from the nixos-oci eval for docs.
        containerLibsMeta = nixosContainerEval.config.nix-lib._libsMeta or { };

        # --- Testing module docs ---

        # Flake-parts eval WITH test modules (for test.oci.* options + test nix-lib).
        # Uses the composed modules from flake.modules.flake.* as single entrypoints.
        testFlakePartsEval =
          inputs.flake-parts.lib.evalFlakeModule
            {
              inputs = inputs // {
                self = {
                  inputs = inputs;
                };
              };
            }
            {
              imports = [
                flakeModules.flake.nix-oci
                flakeModules.flake.nix-oci-test
              ];
              systems = [ system ];
            };

        testPerSystemOptions = testFlakePartsEval.options.perSystem.type.getSubOptions [ ];

        # test.oci.* flake-parts options
        testFlakePartsDoc = pkgs.nixosOptionsDoc {
          options = {
            inherit (testPerSystemOptions) test;
          };
          transformOptions = cleanupOptions;
        };

        # nix-lib docs from the test-aware eval (includes test lib functions).
        # The test eval's nix-lib.docs.package has all functions (main + test).
        # We use it specifically for the testing reference page.
        testNixLibDoc = testFlakePartsEval.config.allSystems.${system}.nix-lib.docs.package or nixLibDoc;

        # Strip NDG/TOML frontmatter (+++ blocks) from markdown files.
        # mdBook doesn't use frontmatter — titles come from SUMMARY.md.
        stripFrontmatter = ''
          strip_toml_frontmatter() {
            local f="$1"
            if head -1 "$f" | grep -q '^+++$'; then
              local end=$(tail -n +2 "$f" | grep -n '^+++$' | head -1 | cut -d: -f1)
              if [ -n "$end" ]; then
                tail -n +$((end + 2)) "$f" > "$f.tmp" && mv "$f.tmp" "$f"
              fi
            fi
          }
        '';

        # Diataxis layout for mdBook:
        #   Root: index.md (overview), getting-started.md (tutorial)
        #   How-to, Architecture, Security, Examples, Reference, Test Reference
        docsInputDir =
          pkgs.runCommand "mdbook-input"
            {
              nativeBuildInputs = [ pkgs.gnused ];
            }
            ''
              ${stripFrontmatter}

              mkdir -p $out/src/{security,architecture,how-to,reference,test-reference,examples}

              # Root pages
              cp ${../README.md} $out/src/index.md
              cp ${../CONTRIBUTING.md} $out/src/contributing.md
              cp ${../docs/content}/getting-started.md $out/src/
              strip_toml_frontmatter $out/src/getting-started.md

              # --- How-to guides ---
              for f in ${../docs/content}/how-to/*.md; do
                cp "$f" $out/src/how-to/
              done
              for f in $out/src/how-to/*.md; do
                strip_toml_frontmatter "$f"
              done

              # --- Thematic explanation pages ---
              cp -r ${../docs/content}/security/. $out/src/security/
              cp -r ${../docs/content}/architecture/. $out/src/architecture/
              chmod -R u+w $out/src/security $out/src/architecture
              for f in $(find $out/src/security $out/src/architecture -name '*.md'); do
                strip_toml_frontmatter "$f"
              done

              # --- Reference: copy templates and inject generated options at markers ---
              for f in ${../docs/content}/reference/*.md; do
                cp "$f" $out/src/reference/
              done
              chmod -R u+w $out/src/reference
              for f in $out/src/reference/*.md; do
                strip_toml_frontmatter "$f"
              done

              sed -i '/<!-- OPTIONS:toplevel -->/r ${topLevelDoc.optionsCommonMark}' $out/src/reference/flake-parts-options.md
              sed -i '/<!-- OPTIONS:persystem -->/r ${perSystemDoc.optionsCommonMark}' $out/src/reference/flake-parts-options.md
              sed -i '/<!-- OPTIONS:container -->/r ${containerDoc.optionsCommonMark}' $out/src/reference/flake-parts-options.md
              sed -i '/<!-- OPTIONS:deploy -->/r ${deployDoc.optionsCommonMark}' $out/src/reference/nixos-options.md
              sed -i '/<!-- OPTIONS:deploy -->/r ${deployDoc.optionsCommonMark}' $out/src/reference/home-manager-options.md
              sed -i '/<!-- OPTIONS:deploy -->/r ${deployDoc.optionsCommonMark}' $out/src/reference/system-manager-options.md
              sed -i '/<!-- OPTIONS:nix-lib -->/r ${nixLibDoc}/nix-lib.md' $out/src/reference/nix-lib.md
              sed -i '/<!-- OPTIONS:nix-lib-nixos-deploy -->/r ${nixLibDoc}/nix-lib-nixos-deploy.md' $out/src/reference/nix-lib-nixos-deploy.md
              sed -i '/<!-- OPTIONS:nix-lib-home-manager-deploy -->/r ${nixLibDoc}/nix-lib-home-manager-deploy.md' $out/src/reference/nix-lib-home-manager-deploy.md
              sed -i '/<!-- OPTIONS:nix-lib-system-manager-deploy -->/r ${nixLibDoc}/nix-lib-system-manager-deploy.md' $out/src/reference/nix-lib-system-manager-deploy.md

              # --- Test reference pages ---
              for f in ${../docs/content}/test-reference/*.md; do
                cp "$f" $out/src/test-reference/
              done
              chmod -R u+w $out/src/test-reference
              for f in $out/src/test-reference/*.md; do
                strip_toml_frontmatter "$f"
              done

              sed -i '/<!-- OPTIONS:testing-flake-parts -->/r ${testFlakePartsDoc.optionsCommonMark}' $out/src/test-reference/testing-flake-parts-options.md
              sed -i '/<!-- OPTIONS:nix-lib-testing -->/r ${testNixLibDoc}/docs.md' $out/src/test-reference/nix-lib-testing.md

              # --- Examples: generate pages with subdir-based sections ---
              gen_examples_page() {
                local title="$1" dest="$2"
                shift 2
                {
                  echo "# $title"
                  echo ""
                  for dir in "$@"; do
                    for f in $(find "$dir" -maxdepth 1 -name '*.nix' -type f | sort); do
                      name="$(basename "$f" .nix)"
                      echo "## $name"
                      echo ""
                      echo '```nix'
                      cat "$f"
                      echo '```'
                      echo ""
                    done
                    for sub in $(find "$dir" -mindepth 1 -maxdepth 1 -type d | sort); do
                      subname="$(basename "$sub")"
                      pretty="$(echo "$subname" | sed 's/-/ /g')"
                      echo "## ''${pretty^}"
                      echo ""
                      for f in $(find "$sub" -name '*.nix' -type f | sort); do
                        name="$(basename "$f" .nix)"
                        echo "### $name"
                        echo ""
                        echo '```nix'
                        cat "$f"
                        echo '```'
                        echo ""
                      done
                    done
                  done
                } > "$dest"
              }

              gen_examples_page "Flake examples" "$out/src/examples/flake.md" \
                "${../examples}/flake"
              gen_examples_page "NixOS deploy" "$out/src/examples/deploy-nixos.md" \
                "${../examples}/deploy-nixos"
              gen_examples_page "Home Manager deploy" "$out/src/examples/deploy-home-manager.md" \
                "${../examples}/deploy-home-manager"
              gen_examples_page "system-manager deploy" "$out/src/examples/deploy-system-manager.md" \
                "${../examples}/deploy-system-manager"

              # --- SUMMARY.md (mdBook sidebar) ---
              cat > $out/src/SUMMARY.md << 'SUMMARY'
              # Summary

              [nix-oci](index.md)
              [Contributing](contributing.md)

              ---

              # Getting Started

              - [Getting Started](getting-started.md)

              ---

              # How-to

              - [Container Modules API](how-to/container-modules-api.md)
              - [NixOS Containers](how-to/nixos-containers.md)
              - [Share Containers Across Modules](how-to/share-containers-across-modules.md)
              - [Deploy Modules](how-to/deploy-modules.md)

              ---

              # Architecture

              - [Overview](architecture/index.md)
              - [Archive-less Container Building](architecture/archive-less-container-building.md)
              - [Automatic Labeling](architecture/automatic-labeling.md)
              - [Automatic Metadata](architecture/automatic-metadata.md)
              - [Container Metadata Wiring](architecture/container-metadata-wiring.md)
              - [Design Choices](architecture/design-choices.md)
              - [OCI Standards Compliance](architecture/oci-standards-compliance.md)
              - [Performance](architecture/performance.md)
              - [Validation-Gated Delivery](architecture/validation-gated-delivery.md)

              ---

              # Security

              - [Overview](security/index.md)
              - [Container Probes](security/container-probes.md)
              - [Hardening](security/hardening.md)
              - [Image Signing](security/image-signing.md)
              - [Policy Coherence Testing](security/policy-coherence-testing.md)
              - [Policy Integrity Testing](security/policy-integrity-testing.md)
              - [Security Defaults](security/security-defaults.md)
              - [Vulnerability Scanning](security/vulnerability-scanning.md)

              ---

              # Examples

              - [Flake examples](examples/flake.md)
              - [NixOS deploy](examples/deploy-nixos.md)
              - [Home Manager deploy](examples/deploy-home-manager.md)
              - [system-manager deploy](examples/deploy-system-manager.md)

              ---

              # Reference

              - [Options: flake-parts](reference/flake-parts-options.md)
              - [Options: NixOS deploy](reference/nixos-options.md)
              - [Options: Home Manager deploy](reference/home-manager-options.md)
              - [Options: system-manager deploy](reference/system-manager-options.md)
              - [nix-lib: flake-parts functions](reference/nix-lib.md)
              - [nix-lib: NixOS deploy functions](reference/nix-lib-nixos-deploy.md)
              - [nix-lib: Home Manager deploy functions](reference/nix-lib-home-manager-deploy.md)
              - [nix-lib: system-manager deploy functions](reference/nix-lib-system-manager-deploy.md)

              ---

              # Test Reference

              - [Options: flake-parts testing](test-reference/testing-flake-parts-options.md)
              - [nix-lib: testing functions](test-reference/nix-lib-testing.md)
              SUMMARY

              # Remove leading whitespace from SUMMARY.md (heredoc indentation)
              sed -i 's/^              //' $out/src/SUMMARY.md

              # --- book.toml ---
              cat > $out/book.toml << 'TOML'
              [book]
              title = "nix-oci"
              description = "Build, harden and deploy OCI containers entirely from Nix"
              authors = ["Dauliac"]
              language = "en"
              src = "src"

              [build]
              build-dir = "book"

              [output.html]
              default-theme = "light"
              preferred-dark-theme = "coal"
              git-repository-url = "https://github.com/Dauliac/nix-oci"
              additional-css = ["theme/custom.css"]
              additional-js = ["theme/mermaid.min.js", "theme/mermaid-init.js"]
              no-section-label = true

              [output.html.search]
              enable = true
              TOML
              sed -i 's/^              //' $out/book.toml

              # --- Theme: custom CSS (Catppuccin) ---
              mkdir -p $out/theme
              cat > $out/theme/custom.css << 'CSS'
              @font-face {
                font-family: "Frames Part One";
                src: url("assets/FramesPartOne-Bold.woff2") format("woff2");
                font-weight: 700;
                font-display: swap;
              }

              :root {
                --sidebar-width: 280px;
              }

              /* Catppuccin Latte (light) overrides */
              .light, .rust {
                --bg: #eff1f5;
                --fg: #4c4f69;
                --sidebar-bg: #e6e9ef;
                --sidebar-fg: #4c4f69;
                --sidebar-active: #df8e1d;
                --links: #df8e1d;
                --inline-code-color: #4c4f69;
                --theme-popup-bg: #e6e9ef;
                --theme-popup-border: #ccd0da;
                --quote-bg: #e6e9ef;
                --quote-border: #df8e1d;
                --table-border-color: #ccd0da;
                --table-header-bg: #e6e9ef;
                --searchbar-border-color: #ccd0da;
                --searchbar-bg: #eff1f5;
                --searchbar-fg: #4c4f69;
              }

              /* Catppuccin Mocha (dark) overrides */
              .coal, .navy, .ayu {
                --bg: #1e1e2e;
                --fg: #cdd6f4;
                --sidebar-bg: #181825;
                --sidebar-fg: #cdd6f4;
                --sidebar-active: #f9e2af;
                --links: #f9e2af;
                --inline-code-color: #cdd6f4;
                --theme-popup-bg: #181825;
                --theme-popup-border: #313244;
                --quote-bg: #313244;
                --quote-border: #f9e2af;
                --table-border-color: #45475a;
                --table-header-bg: #313244;
                --searchbar-border-color: #313244;
                --searchbar-bg: #1e1e2e;
                --searchbar-fg: #cdd6f4;
              }

              body {
                font-family: "Iosevka", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
              }

              code, pre, .hljs {
                font-family: "Iosevka", monospace;
              }

              h1:first-of-type {
                font-family: "Frames Part One", monospace;
                font-weight: 700;
                letter-spacing: -0.02em;
              }

              .sidebar .sidebar-scrollbox a.active {
                font-weight: 700;
              }
              CSS

              # --- Mermaid support ---
              cat > $out/theme/mermaid-init.js << 'MERMJS'
              document.addEventListener("DOMContentLoaded", function() {
                if (typeof mermaid !== "undefined") {
                  mermaid.initialize({
                    startOnLoad: false,
                    theme: "base",
                    themeVariables: {
                      primaryColor: "#fff8e1",
                      primaryTextColor: "#333",
                      primaryBorderColor: "#e0a800",
                      lineColor: "#d4a017",
                      fontFamily: "'Iosevka', monospace",
                      fontSize: "16px"
                    }
                  });
                  document.querySelectorAll("code.language-mermaid").forEach(function(el) {
                    var pre = el.parentElement;
                    pre.classList.add("mermaid");
                    pre.textContent = el.textContent;
                  });
                  mermaid.run();
                }
              });
              MERMJS

              # Copy assets into src so mdBook can serve them
              mkdir -p $out/src/assets
              cp -r ${../docs/assets}/. $out/src/assets/
            '';

        # --- mdBook site build ---
        docs =
          pkgs.runCommandLocal "nix-oci-docs"
            {
              nativeBuildInputs = [ pkgs.mdbook ];
            }
            ''
              cp -r ${docsInputDir}/. build/
              chmod -R u+w build/

              # Fetch mermaid.min.js for offline use
              cp ${
                pkgs.fetchurl {
                  url = "https://cdn.jsdelivr.net/npm/mermaid@11.4.1/dist/mermaid.min.js";
                  hash = "sha256-pDvBr9RG+cTMZqxd1F0C6NZeJvxTROwO94f4jW3bb54=";
                }
              } build/theme/mermaid.min.js

              cd build
              mdbook build
              mv book $out
            '';
      in
      {
        # nix-lib docs: multi-page output with fn body extraction
        nix-lib.docs = {
          src = ../.;
          pages = {
            nix-lib = {
              showIndex = false;
              showTitle = false;
              headingLevel = 2;
              header = ''
                Library functions available as `config.lib.oci.*` (per-system) after importing the nix-oci flake-parts module.

                ## Overriding functions

                All nix-oci library functions can be overridden by consumers. Since they are declared as `nix-lib.lib.oci.*` module options, you can replace any function in your own flake-parts module:

                ```nix
                # In your flake module:
                perSystem = { lib, ... }: {
                  nix-lib.lib.oci.mkAutoLabels = {
                    type = lib.types.functionTo lib.types.attrs;
                    description = "My custom label generator";
                    fn = { ... }: {
                      # your custom labels
                    };
                  };
                };
                ```

                The overridden function will be used everywhere nix-oci calls `config.lib.oci.mkAutoLabels`, including image builders and deploy modules. This lets you customize or extend any behavior without forking nix-oci.

                See also:

                - [Source: `nix/modules/oci/lib/`](https://github.com/Dauliac/nix-oci/tree/main/nix/modules/oci/lib) -- image builders, layers, labels, security, ports, architecture
                - [Source: `nix/modules/oci/security/`](https://github.com/Dauliac/nix-oci/tree/main/nix/modules/oci/security) -- CVE, SBOM, signing, compliance, credentials leak, linting
                - [Source: `nix/modules/oci/testing/`](https://github.com/Dauliac/nix-oci/tree/main/nix/modules/oci/testing) -- CST, dgoss, dive, container probes

                ---
              '';
            };
            nix-lib-nixos-deploy = {
              showIndex = false;
              showTitle = false;
              headingLevel = 2;
              header = ''
                Deploy helper functions available in NixOS deploy scope.

                The pure deploy helpers (`copyScript`, `mkPerfOpts`, `allHostPorts`, `mkRunArgs`,
                `autoStartContainers`) are shared across all deploy targets and documented on the
                [flake-parts functions](nix-lib.html) page under `oci.deploy.*`.

                ---
              '';
            };
            nix-lib-home-manager-deploy = {
              showIndex = false;
              showTitle = false;
              headingLevel = 2;
              header = ''
                Deploy helper functions available in Home Manager deploy scope.

                The pure deploy helpers are shared across all deploy targets and documented on the
                [flake-parts functions](nix-lib.html) page under `oci.deploy.*`.

                ---
              '';
            };
            nix-lib-system-manager-deploy = {
              showIndex = false;
              showTitle = false;
              headingLevel = 2;
              header = ''
                Deploy helper functions available in system-manager deploy scope.

                The pure deploy helpers are shared across all deploy targets and documented on the
                [flake-parts functions](nix-lib.html) page under `oci.deploy.*`.

                ---
              '';
            };
          };
        };

        legacyPackages = {
          docs-github-workflows = config.githubActions.workflowsDir;
          inherit docs;
        };

        # GitHub Actions workflows
        githubActions = {
          enable = true;

          # CI: run all checks on PRs and main pushes
          workflows.ci = {
            name = "CI";

            on = {
              pullRequest = { };
              push.branches = [ "main" ];
            };

            concurrency = {
              group = "ci-\${{ github.ref }}";
              cancelInProgress = true;
            };

            jobs.check = {
              runsOn = "ubuntu-latest";
              steps = [
                {
                  name = "Checkout";
                  uses = "actions/checkout@v4";
                }
                {
                  name = "Install Nix";
                  uses = "DeterminateSystems/nix-installer-action@main";
                }
                {
                  name = "Cache Nix store";
                  uses = "DeterminateSystems/magic-nix-cache-action@main";
                }
                {
                  name = "Check flake";
                  run = "nix flake check --print-build-logs";
                }
              ];
            };
          };

          # Docs: build and deploy to GitHub Pages
          workflows.deploy-docs = {
            name = "Deploy Documentation";

            on = {
              push.branches = [ "main" ];
              workflowDispatch = { };
            };

            permissions = {
              contents = "read";
              pages = "write";
              id-token = "write";
            };

            concurrency = {
              group = "pages";
              cancelInProgress = false;
            };

            jobs.build = {
              runsOn = "ubuntu-latest";
              steps = [
                {
                  name = "Checkout";
                  uses = "actions/checkout@v4";
                }
                {
                  name = "Install Nix";
                  uses = "DeterminateSystems/nix-installer-action@main";
                }
                {
                  name = "Cache Nix store";
                  uses = "DeterminateSystems/magic-nix-cache-action@main";
                }
                {
                  name = "Build documentation";
                  run = "nix build .#legacyPackages.x86_64-linux.docs";
                }
                {
                  name = "Upload artifact";
                  uses = "actions/upload-pages-artifact@v3";
                  with_ = {
                    path = "result";
                  };
                }
              ];
            };

            jobs.deploy = {
              runsOn = "ubuntu-latest";
              needs = [ "build" ];
              environment = {
                name = "github-pages";
                url = "\${{ steps.deployment.outputs.page_url }}";
              };
              steps = [
                {
                  id = "deployment";
                  name = "Deploy to GitHub Pages";
                  uses = "actions/deploy-pages@v4";
                }
              ];
            };
          };
        };
      };
  };
}
