# Unified generated labels option.
#
# Any _nixos-oci module can contribute OCI labels here. These are merged
# into the image manifest by the build function.
#
# Replaces the scattered _output.{hardening,performance,gpu}.labels
# with a single composable attrset.
#
# Examples:
#   - performance/outputs.nix adds allocator, tunables, compiler labels
#   - hardening/outputs.nix adds seccomp, capabilities, rootfs labels
#   - gpu/outputs.nix adds CUDA capability labels
{ lib, ... }:
{
  options.oci.container.generatedLabels = lib.mkOption {
    type = lib.types.attrsOf lib.types.str;
    default = { };
    description = ''
      OCI labels generated by _nixos-oci modules.

      Any module can contribute labels by setting this option. All
      contributions are merged (later modules override earlier ones
      for the same key). The build function merges these with
      user-provided `labels` (user labels take priority).

      This replaces the previous pattern of scattered
      `_output.{hardening,performance,gpu}.labels`.
    '';
  };
}
